[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "calib_commons"
version = "0.2.0"
description = ""
authors = [
    { name = "Flueckiger Tim", email = "timflueckiger@outlook.com" }
]
dependencies = [
    "numpy",
    "opencv-python",
    "scipy",
    "matplotlib",
    "tqdm"
]
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]

[project.scripts]
calibrate-intrinsics = "calib_commons.scripts.internal_calibration:main"
center-to-dslr = "calib_commons.scripts.center_to_dslr:main"